name: Build NinjaScript Strategies (Windows)

on:
  push:
    paths:
      - '**.cs'
  pull_request:
    paths:
      - '**.cs'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Copy NinjaTrader DLLs (if needed)
        run: |
          mkdir -p $env:USERPROFILE\.nuget\packages
          # If you have DLLs in a 'libs' folder, copy them to output or reference them in your .csproj

      - name: Restore dependencies
        run: dotnet restore || true

      - name: Build all C# projects
        run: |
          for /r %%f in (*.csproj) do dotnet build "%%f" --configuration Release
